export const jeonsesagi = [
  {
    category: "전세사기",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "전세사기",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "전세사기",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
];
export const senghalbi = [
  {
    category: "생활비",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "생활비",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "생활비",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
];

export const byungwonbi = [
  {
    category: "병원비",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "병원비",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "병원비",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
];
export const dobak = [
  {
    category: "도박",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "도박",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "도박",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
];
export const coin = [
  {
    category: "코인",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "코인",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "코인",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
];
export const joosick = [
  {
    category: "주식",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "주식",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "주식",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
];
export const saup = [
  {
    category: "사업실패",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "사업실패",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "사업실패",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
];
export const sachi = [
  {
    category: "사치",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "사치",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "사치",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
];
export const voicefishing = [
  {
    category: "보이스피싱",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "보이스피싱",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "보이스피싱",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
];
export const boodongsan = [
  {
    category: "부동산투자",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "부동산투자",
    name: "한**",
    desc: "40대 남성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
  {
    category: "부동산투자",
    name: "한**",
    desc: "40대 여성",
    job: "직장인",
    loc: "부산",
    income: "185만원",
    debt: "7천만원원",
  },
];
